# Generated by Django 3.2.4 on 2021-07-23 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0001_initial'),
        ('travels_app', '0003_auto_20210720_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='planner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_planners', to='login_registration_app.user'),
        ),
    ]
